### ISSUE TITLE
Rework permissions storage

### ISSUE THREAD

**Issue by KallynGowdy** [casual-simulation/casualos#313]
Currently, permissions are managed by policies, which are objects that contain a list of permissions that relate a role to an action. We want permissions to be more granular (supporting permissions directly to a user for a specific resource) and have better capabilities (supporting querying by resource, by marker, by role, by user ID, by inst ID, etc.).

This issue tracks work on this task to create tables which are able to store granular permissions and rework the backend to use granular permissions. Currently, on ab1.bot, there are only 3 user-created policies. Each policy only has a single permission. As a result, we can make this a breaking change and then migrate those policies manually if needed.

### Tasks

- [x] Update PolicyController
- [x] Fix Tests
    - [x] DataRecordsController
    - [x] FileRecordsController
    - [x] EventRecordsController
    - [x] WebsocketController
    - [x] RecordsServer
- [x] Update API
    - [x] Add `os.listDataByMarker()`
    - [x] Rework `os.grantRecordMarkerPermission()`
    - [x] Rework `os.revokeRecordMarkerPermission()`
    - [x] Enforce marker length limit (30 chars)
- [x] Update Dashboard
    - [x] Rework "Roles" and "Policies" tab into "Permissions" tab
- [x] Update CHANGELOG
- [x] Allow "sub-folders" for markers
    - [x] `marker:folder` syntax
    - [x] PolicyController
        - [x] `POST /api/v2/records/permissions`
        - [x] `GET /api/v2/records/permissions/list`
    - [x] DataRecordsController
